packages:
  - "web"
  - "worker"
  - "standalone"
  - "packages/**"
allowBuilds:
  esbuild: true
  sharp: true
  better-sqlite3: true
supportedArchitectures:
  os: [ win32 ]
  cpu: [ x64 ]
  libc: [ msvc ]
